// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";

function let_(promise, callback) {
  return promise.then(Curry.__1(callback));
}

function resolve(prim) {
  return Promise.resolve(prim);
}

function reject(prim) {
  return Promise.reject(prim);
}

function async(x) {
  return Promise.resolve(x);
}

function $$catch(promise, callback) {
  return promise.catch(Curry.__1(callback));
}

var then_ = let_;

export {
  let_ ,
  resolve ,
  reject ,
  async ,
  then_ ,
  $$catch ,
  
}
/* No side effect */
