// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

function BeaconList(Props) {
  var data = Props.data;
  return React.createElement(ReactNative.FlatList, {
              data: data,
              keyExtractor: (function (param, i) {
                  return i.toString();
                }),
              renderItem: (function (param) {
                  var item = param.item;
                  return React.createElement(ReactNative.View, {
                              children: null
                            }, React.createElement(ReactNative.Text, {
                                  children: item.uid
                                }), React.createElement(ReactNative.Text, {
                                  children: item.rssi.toString()
                                }), React.createElement(ReactNative.Text, {
                                  children: item.txPower.toString()
                                }));
                })
            });
}

var make = BeaconList;

export {
  make ,
  
}
/* react Not a pure module */
