// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactNativeEddystone from "@lg2/react-native-eddystone";

function useScanner(param) {
  var match = React.useState(function () {
        return false;
      });
  var scanning = match[0];
  var match$1 = React.useState(function () {
        return {
                beacons: [{
                    id: "0",
                    uid: "0x00",
                    rssi: 0.1,
                    txPower: 0.01
                  }]
              };
      });
  var setBeacons = match$1[1];
  var beaconListener = function (d) {
    return Curry._1(setBeacons, (function (beacons) {
                  return {
                          beacons: [d].concat(beacons.beacons).slice(0, 10)
                        };
                }));
  };
  React.useEffect((function () {
          ReactNativeEddystone.default.addListener("onUIDFrame", beaconListener);
          ReactNativeEddystone.default.startScanning();
          return (function (param) {
                    ReactNativeEddystone.default.stopScanning();
                    ReactNativeEddystone.default.removeListener("onUIDFrame", beaconListener);
                    
                  });
        }), [scanning]);
  return [
          match$1[0],
          scanning,
          match[1]
        ];
}

export {
  useScanner ,
  
}
/* react Not a pure module */
