// Generated by ReScript, PLEASE EDIT WITH CARE

import * as IBeacon from "./IBeacon";

function useScanner(prim) {
  return IBeacon.useScanner();
}

export {
  useScanner ,
  
}
/* ./IBeacon Not a pure module */
