// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Async from "./Async.bs.js";
import * as Fetch from "bs-fetch/src/Fetch.bs.js";
import * as Citizen from "./core/Citizen.bs.js";
import * as Belt_Result from "bs-platform/lib/es6/belt_Result.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

var endpoint = "https://uitc.pominwu.org/";

function postQuery(query) {
  return fetch(endpoint, Fetch.RequestInit.make(/* Post */2, {
                    "Content-Type": "application/json"
                  }, Caml_option.some(query), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(undefined));
}

function citizen(id) {
  return Async.then_(Async.then_(Async.then_(postQuery(Citizen.one(id)), (function (prim) {
                        return prim.json();
                      })), (function (json) {
                    return Async.async(Belt_Result.getExn(Citizen.one_result_decode(json)));
                  })), (function (data) {
                return Async.async(data.data.citizen);
              }));
}

function allCitizens(param) {
  return Async.then_(Async.then_(Async.then_(postQuery(Citizen.all(undefined)), (function (prim) {
                        return prim.json();
                      })), (function (json) {
                    return Async.async(Belt_Result.getExn(Citizen.all_result_decode(json)));
                  })), (function (data) {
                return Async.async(data.data.allCitizens);
              }));
}

export {
  endpoint ,
  postQuery ,
  citizen ,
  allCitizens ,
  
}
/* No side effect */
