// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Async from "./Async.bs.js";
import * as Fetch from "bs-fetch/src/Fetch.bs.js";
import * as Citizen from "./core/Citizen.bs.js";
import * as Belt_Result from "bs-platform/lib/es6/belt_Result.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

var endpoint = "https://uitc.pominwu.org/";

function citizen(id) {
  return Async.then_(Async.then_(fetch(endpoint, Fetch.RequestInit.make(/* Post */2, {
                            "Content-Type": "application/json"
                          }, Caml_option.some(Citizen.one(id)), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(undefined)), (function (prim) {
                    return prim.json();
                  })), (function (json) {
                return Async.async(Belt_Result.getExn(Citizen.one_result_decode(json)));
              }));
}

function allCitizens(param) {
  return [];
}

export {
  endpoint ,
  citizen ,
  allCitizens ,
  
}
/* No side effect */
