// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function useLoading(param) {
  var match = React.useState(function () {
        return 1;
      });
  var setCount = match[1];
  React.useEffect((function () {
          var task = setInterval((function (param) {
                  return Curry._1(setCount, (function (c) {
                                if (c > 20) {
                                  return 1;
                                } else {
                                  return c + 1 | 0;
                                }
                              }));
                }), 1200);
          return (function (param) {
                    clearInterval(task);
                    
                  });
        }), []);
  return match[0];
}

export {
  useLoading ,
  
}
/* react Not a pure module */
