// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Pervasives from "bs-platform/lib/es6/pervasives.js";

var stateContext = React.createContext([
      /* Start */0,
      (function (param) {
          
        })
    ]);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = stateContext.Provider;

function useContext(param) {
  return React.useContext(stateContext);
}

function take(action, currentState) {
  switch (action) {
    case /* PairBeacon */0 :
        if (currentState !== 0) {
          return Pervasives.failwith("Invalid action at current state");
        } else {
          return /* ScanningBeacon */1;
        }
    case /* SaveBeacon */1 :
        if (currentState !== 1) {
          return Pervasives.failwith("Invalid action at current state");
        } else {
          return /* BeaconPaired */2;
        }
    case /* ConfirmBeaconSaved */2 :
        if (currentState !== 2) {
          return Pervasives.failwith("Invalid action at current state");
        } else {
          return /* Start */0;
        }
    
  }
}

export {
  stateContext ,
  makeProps ,
  make ,
  useContext ,
  take ,
  
}
/* stateContext Not a pure module */
