// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Pervasives from "bs-platform/lib/es6/pervasives.js";

function next(action, currentState) {
  switch (action) {
    case /* PairBeacon */0 :
        if (currentState !== 0) {
          return Pervasives.failwith("Invalid action at current state");
        } else {
          return /* ScanningBeacon */1;
        }
    case /* SaveBeacon */1 :
        if (currentState !== 1) {
          return Pervasives.failwith("Invalid action at current state");
        } else {
          return /* BeaconPaired */2;
        }
    case /* ConfirmBeaconSaved */2 :
        if (currentState !== 2) {
          return Pervasives.failwith("Invalid action at current state");
        } else {
          return /* Start */0;
        }
    
  }
}

export {
  next ,
  
}
/* No side effect */
