// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Pervasives from "bs-platform/lib/es6/pervasives.js";

var stateContext = React.createContext([
      /* Start */0,
      (function (param) {
          
        })
    ]);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = stateContext.Provider;

function useContext(param) {
  return React.useContext(stateContext);
}

function take(action, currentState) {
  if (typeof action === "number") {
    if (action !== 0) {
      if (typeof currentState === "number") {
        return Pervasives.failwith("Invalid action at current state");
      } else {
        return /* Start */0;
      }
    } else if (typeof currentState === "number" && currentState === 0) {
      return /* ScanningBeacon */1;
    } else {
      return Pervasives.failwith("Invalid action at current state");
    }
  } else if (typeof currentState === "number" && currentState === 1) {
    return /* BeaconPaired */{
            _0: action._0
          };
  } else {
    return Pervasives.failwith("Invalid action at current state");
  }
}

export {
  stateContext ,
  makeProps ,
  make ,
  useContext ,
  take ,
  
}
/* stateContext Not a pure module */
