// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Async from "./Async.bs.js";
import * as Beacon from "./core/Beacon.bs.js";
import * as Citizen from "./core/Citizen.bs.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as AsyncStorage from "@react-native-community/async-storage";

function saveBeacon(beacon) {
  return AsyncStorage.default.setItem("beacon", Beacon.toString(beacon));
}

function loadBeacon(param) {
  return Async.then_(AsyncStorage.default.getItem("beacon"), (function (idOrNull) {
                return Async.async(Belt_Option.map(idOrNull === null ? undefined : Caml_option.some(idOrNull), Beacon.fromString));
              }));
}

function saveUser(user) {
  return AsyncStorage.default.setItem("user", Citizen.toString(user));
}

function loadUser(param) {
  return Async.then_(AsyncStorage.default.getItem("user"), (function (idOrNull) {
                return Async.async(Belt_Option.map(idOrNull === null ? undefined : Caml_option.some(idOrNull), Citizen.fromString));
              }));
}

export {
  saveBeacon ,
  loadBeacon ,
  saveUser ,
  loadUser ,
  
}
/* @react-native-community/async-storage Not a pure module */
