// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Pathogen = {};

var Antibody = {};

var Vaccine = {};

var Infection = {};

var Vaccination = {};

var Immunity = {};

var Citizen = {};

var ProximityObservation = {};

var Resolvers = {};

exports.Pathogen = Pathogen;
exports.Antibody = Antibody;
exports.Vaccine = Vaccine;
exports.Infection = Infection;
exports.Vaccination = Vaccination;
exports.Immunity = Immunity;
exports.Citizen = Citizen;
exports.ProximityObservation = ProximityObservation;
exports.Resolvers = Resolvers;
/* No side effect */
