// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Db from "../Db.bs.js";
import * as Async from "../Async.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as $$Storage from "../Storage.bs.js";
import * as ReactNative from "react-native";
import * as StateProvider from "../StateProvider.bs.js";

function LoadUserScreen(Props) {
  var beacon = Props.beacon;
  var match = StateProvider.useContext(undefined);
  var setAppState = match[1];
  React.useEffect((function () {
          var id = String(beacon.minor);
          Async.$$catch(Async.then_(Async.then_(Db.citizen(id), (function (data) {
                          var user = data.data.citizen;
                          return Async.then_($$Storage.saveUser(user), (function (param) {
                                        return Async.async(user);
                                      }));
                        })), (function (user) {
                      var partial_arg = {
                        TAG: /* SaveUser */1,
                        _0: user
                      };
                      return Async.async(Curry._1(setAppState, (function (param) {
                                        return StateProvider.take(partial_arg, param);
                                      })));
                    })), (function (err) {
                  return Async.async((console.log(err), undefined));
                }));
          
        }), []);
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNative.View, {
                  children: React.createElement(ReactNative.Text, {
                        children: "Loading user data from beacon " + String(beacon.minor)
                      })
                }));
}

var make = LoadUserScreen;

export {
  make ,
  
}
/* react Not a pure module */
