// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Async from "../Async.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as $$Storage from "../Storage.bs.js";
import * as ReactNative from "react-native";
import * as StateProvider from "../StateProvider.bs.js";

function LoadUserScreen(Props) {
  var beacon = Props.beacon;
  var match = StateProvider.useContext(undefined);
  var setAppState = match[1];
  React.useEffect((function () {
          setTimeout((function (param) {
                  var user_id = beacon.id;
                  var user_infections = [];
                  var user_vaccinations = [];
                  var user_immunities = [];
                  var user = {
                    id: user_id,
                    infections: user_infections,
                    vaccinations: user_vaccinations,
                    immunities: user_immunities
                  };
                  Async.then_($$Storage.saveUser(user), (function (param) {
                          var partial_arg = {
                            TAG: /* SaveUser */1,
                            _0: user
                          };
                          return Async.async(Curry._1(setAppState, (function (param) {
                                            return StateProvider.take(partial_arg, param);
                                          })));
                        }));
                  
                }), 2000);
          
        }), []);
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNative.View, {
                  children: React.createElement(ReactNative.Text, {
                        children: "Loading user data from beacon " + beacon.id
                      })
                }));
}

var make = LoadUserScreen;

export {
  make ,
  
}
/* react Not a pure module */
