// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Db from "../Db.bs.js";
import * as Async from "../Async.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Beacon from "../core/Beacon.bs.js";
import * as Loading from "../Loading.bs.js";
import * as $$Storage from "../Storage.bs.js";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";
import * as ScreenStyle from "../styles/ScreenStyle.bs.js";
import * as ReactNative from "react-native";
import * as StateProvider from "../StateProvider.bs.js";
import * as Caml_splice_call from "bs-platform/lib/es6/caml_splice_call.js";

function LoadUserScreen(Props) {
  var beacon = Props.beacon;
  var match = StateProvider.useContext(undefined);
  var setAppState = match[1];
  React.useEffect((function () {
          var id = Beacon.toCitizenId(beacon);
          Async.$$catch(Async.then_(Async.then_(Db.citizen(id), (function (user) {
                          return Async.then_($$Storage.saveUser(user), (function (param) {
                                        return Async.async(user);
                                      }));
                        })), (function (user) {
                      var partial_arg = {
                        TAG: /* SaveUser */1,
                        _0: user
                      };
                      return Async.async(Curry._1(setAppState, (function (param) {
                                        return StateProvider.take(partial_arg, param);
                                      })));
                    })), (function (err) {
                  return Async.async((console.log(err), undefined));
                }));
          
        }), []);
  var count = Loading.useLoading(undefined);
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNative.View, {
                  children: React.createElement(ReactNative.Text, {
                        style: ScreenStyle.styles.text,
                        children: "Loading user data" + Caml_splice_call.spliceObjApply("", "concat", [Caml_array.caml_make_vect(count, ".")])
                      })
                }));
}

var make = LoadUserScreen;

export {
  make ,
  
}
/* react Not a pure module */
