// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

function Logo(Props) {
  return React.createElement(ReactNative.Image, {
              source: require("../images/logo.png")
            });
}

var make = Logo;

export {
  make ,
  
}
/* react Not a pure module */
