// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Monitor from "../Monitor.bs.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as ReactNative from "react-native";

function MonitorScreen(Props) {
  var user = Props.user;
  var match = Monitor.useMonitor(user);
  var danger = match[1];
  var tmp;
  if (danger !== undefined) {
    var neighbor = danger[0];
    tmp = neighbor.citizen.id + " within " + String(neighbor.distanceInMeters) + " meter(s) is dangerous because of " + danger[1].name;
  } else {
    tmp = "No danger";
  }
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNative.View, {
                  children: null
                }, React.createElement(ReactNative.Text, {
                      children: "Monitor"
                    }), React.createElement(ReactNative.Text, {
                      children: Belt_Option.getWithDefault(Belt_Option.map(match[0], (function (neighbors) {
                                  return String(neighbors.length) + " neighbors";
                                })), "No results yet")
                    }), React.createElement(ReactNative.Text, {
                      children: tmp
                    })));
}

var make = MonitorScreen;

export {
  make ,
  
}
/* react Not a pure module */
