// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Logo from "./Logo.bs.js";
import * as React from "react";
import * as ScreenStyle from "../styles/ScreenStyle.bs.js";
import * as ReactNative from "react-native";
import * as StateProvider from "../StateProvider.bs.js";

function NeedPermissionScreen(Props) {
  React.useContext(StateProvider.stateContext);
  return React.createElement(ReactNative.View, {
              style: {
                alignItems: "center",
                maxWidth: 300
              },
              children: null
            }, React.createElement(Logo.make, {}), React.createElement(ReactNative.Text, {
                  style: [
                    ScreenStyle.styles.text,
                    {
                      paddingTop: 14
                    }
                  ],
                  children: "Ultra Immune Taipei City needs you to grant Location permission in order to protect you.  Please grant Location permissions manually in Android settings."
                }));
}

var make = NeedPermissionScreen;

export {
  make ,
  
}
/* Logo Not a pure module */
