// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as BeaconList from "./BeaconList.bs.js";
import * as ReactNative from "react-native";
import * as BeaconScanner from "../BeaconScanner.bs.js";

function ScannerScreen(Props) {
  var match = BeaconScanner.useScanner(undefined);
  var setScanning = match[2];
  return React.createElement(ReactNative.View, {
              children: null
            }, React.createElement(BeaconList.make, {
                  data: match[0]
                }), React.createElement(ReactNative.Button, {
                  onPress: (function (param) {
                      return Curry._1(setScanning, (function (s) {
                                    return !s;
                                  }));
                    }),
                  title: match[1] ? "Stop" : "Start"
                }));
}

var make = ScannerScreen;

export {
  make ,
  
}
/* react Not a pure module */
