// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";
import * as StateProvider from "../StateProvider.bs.js";

function WarnScreen(Props) {
  React.useContext(StateProvider.stateContext);
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNative.View, {
                  children: React.createElement(ReactNative.Text, {
                        children: "Warning!"
                      })
                }));
}

var make = WarnScreen;

export {
  make ,
  
}
/* react Not a pure module */
