// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Monitor from "../Monitor.bs.js";
import * as ReactNative from "react-native";
import * as StateProvider from "../StateProvider.bs.js";

function WarnScreen(Props) {
  var user = Props.user;
  var neighbor = Props.neighbor;
  var pathogen = Props.pathogen;
  var match = React.useContext(StateProvider.stateContext);
  var match$1 = Monitor.useMonitor(undefined, user, match[1]);
  var setDanger = match$1[2];
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNative.View, {
                  children: null
                }, React.createElement(ReactNative.Text, {
                      children: "Warning!"
                    }), React.createElement(ReactNative.Text, {
                      children: "This person " + neighbor.citizen.id + " is dangerous to you."
                    }), React.createElement(ReactNative.Text, {
                      children: "Carries " + pathogen.name + " within " + String(neighbor.distanceInMeters) + " meters."
                    }), React.createElement(ReactNative.Button, {
                      onPress: (function (param) {
                          return Curry._1(setDanger, (function (param) {
                                        
                                      }));
                        }),
                      title: "Danger cleared"
                    })));
}

var make = WarnScreen;

export {
  make ,
  
}
/* react Not a pure module */
