// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";

var styles = ReactNative.StyleSheet.create({
      background: {
        backgroundColor: "#000000",
        alignItems: "center",
        flex: 1,
        justifyContent: "center"
      }
    });

export {
  styles ,
  
}
/* styles Not a pure module */
