// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";

function fromEddystone(b) {
  return {
          id: b.id,
          uid: b.uid,
          rssi: b.rssi,
          txPower: b.txPower
        };
}

function toString(beacon) {
  return Belt_Option.getExn(JSON.stringify(beacon));
}

function fromString(prim) {
  return JSON.parse(prim);
}

export {
  fromEddystone ,
  toString ,
  fromString ,
  
}
/* No side effect */
