// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";

function toString(beacon) {
  return Belt_Option.getExn(JSON.stringify(beacon));
}

function fromString(prim) {
  return JSON.parse(prim);
}

function toCitizenId(beacon) {
  return String(beacon.minor);
}

export {
  toString ,
  fromString ,
  toCitizenId ,
  
}
/* No side effect */
