// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";

function query(id) {
  return "\n  citizen(id: " + id + ") {\n    id\n    infections { pathogen { name } }\n    vaccinations { vaccine { name } }\n    immunities { antibody { name, bindsTo { name } } expiresAt }\n  }\n";
}

function to_string(user) {
  return Belt_Option.getExn(JSON.stringify(user));
}

function from_string(prim) {
  return JSON.parse(prim);
}

var queryAll = "\n  allCitizens {\n    id\n    infections { pathogen { name } }\n    vaccinations { vaccine { name } }\n    immunities { antibody { name, bindsTo { name } } expiresAt }\n  }\n`\n";

export {
  query ,
  queryAll ,
  to_string ,
  from_string ,
  
}
/* No side effect */
