// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Decco from "decco/src/Decco.bs.js";
import * as Belt_Result from "bs-platform/lib/es6/belt_Result.js";

function t_decode(json) {
  return Belt_Result.map(Decco.stringFromJson(json), (function (prim) {
                return new Date(prim);
              }));
}

function t_encode(date) {
  return Decco.stringToJson(date.toJSON());
}

export {
  t_decode ,
  t_encode ,
  
}
/* No side effect */
