// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Date from "./Date.bs.js";
import * as Decco from "decco/src/Decco.bs.js";
import * as Js_dict from "bs-platform/lib/es6/js_dict.js";
import * as Js_json from "bs-platform/lib/es6/js_json.js";
import * as Antibody from "./Antibody.bs.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";

function t_encode(v) {
  return Js_dict.fromArray([
              [
                "antibody",
                Antibody.t_encode(v.antibody)
              ],
              [
                "expiresAt",
                $$Date.t_encode(v.expiresAt)
              ]
            ]);
}

function t_decode(v) {
  var dict = Js_json.classify(v);
  if (typeof dict === "number") {
    return Decco.error(undefined, "Not an object", v);
  }
  if (dict.TAG !== /* JSONObject */2) {
    return Decco.error(undefined, "Not an object", v);
  }
  var dict$1 = dict._0;
  var antibody = Antibody.t_decode(Belt_Option.getWithDefault(Js_dict.get(dict$1, "antibody"), null));
  if (antibody.TAG === /* Ok */0) {
    var expiresAt = $$Date.t_decode(Belt_Option.getWithDefault(Js_dict.get(dict$1, "expiresAt"), null));
    if (expiresAt.TAG === /* Ok */0) {
      return {
              TAG: /* Ok */0,
              _0: {
                antibody: antibody._0,
                expiresAt: expiresAt._0
              }
            };
    }
    var e = expiresAt._0;
    return {
            TAG: /* Error */1,
            _0: {
              path: ".expiresAt" + e.path,
              message: e.message,
              value: e.value
            }
          };
  }
  var e$1 = antibody._0;
  return {
          TAG: /* Error */1,
          _0: {
            path: ".antibody" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
}

export {
  t_encode ,
  t_decode ,
  
}
/* No side effect */
