// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Date from "./Date.bs.js";
import * as Decco from "decco/src/Decco.bs.js";
import * as Js_dict from "bs-platform/lib/es6/js_dict.js";
import * as Js_json from "bs-platform/lib/es6/js_json.js";
import * as Pathogen from "./Pathogen.bs.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";

function t_encode(v) {
  return Js_dict.fromArray([
              [
                "pathogen",
                Pathogen.t_encode(v.pathogen)
              ],
              [
                "infectedAt",
                $$Date.t_encode(v.infectedAt)
              ]
            ]);
}

function t_decode(v) {
  var dict = Js_json.classify(v);
  if (typeof dict === "number") {
    return Decco.error(undefined, "Not an object", v);
  }
  if (dict.TAG !== /* JSONObject */2) {
    return Decco.error(undefined, "Not an object", v);
  }
  var dict$1 = dict._0;
  var pathogen = Pathogen.t_decode(Belt_Option.getWithDefault(Js_dict.get(dict$1, "pathogen"), null));
  if (pathogen.TAG === /* Ok */0) {
    var infectedAt = $$Date.t_decode(Belt_Option.getWithDefault(Js_dict.get(dict$1, "infectedAt"), null));
    if (infectedAt.TAG === /* Ok */0) {
      return {
              TAG: /* Ok */0,
              _0: {
                pathogen: pathogen._0,
                infectedAt: infectedAt._0
              }
            };
    }
    var e = infectedAt._0;
    return {
            TAG: /* Error */1,
            _0: {
              path: ".infectedAt" + e.path,
              message: e.message,
              value: e.value
            }
          };
  }
  var e$1 = pathogen._0;
  return {
          TAG: /* Error */1,
          _0: {
            path: ".pathogen" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
}

export {
  t_encode ,
  t_decode ,
  
}
/* No side effect */
