// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function fromBeaconsWithCitizens(_beacons, _citizens) {
  
}

function dangeredBy(user, neighbors) {
  var immunes = Belt_Array.reduce(Belt_Array.map(user.immunities, (function (i) {
              return Belt_Array.map(i.antibody.bindsTo, (function (p) {
                            return p.name;
                          }));
            })), [], Belt_Array.concat);
  return Belt_Array.reduce(Belt_Array.map(neighbors, (function (param) {
                    return Belt_Array.map(Belt_Array.keep(Belt_Array.keep(param.citizen.infections, (function (inf) {
                                          return !Belt_Array.some(immunes, (function (immune) {
                                                        return immune === inf.pathogen.name;
                                                      }));
                                        })), (function (inf) {
                                      return param.distanceInMeters < inf.pathogen.spreadDistanceInMeters;
                                    })), (function (inf) {
                                  return [
                                          param,
                                          inf.pathogen
                                        ];
                                }));
                  })), [], Belt_Array.concat);
}

export {
  fromBeaconsWithCitizens ,
  dangeredBy ,
  
}
/* No side effect */
