// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Date from "./Date.bs.js";
import * as Decco from "decco/src/Decco.bs.js";
import * as Js_dict from "bs-platform/lib/es6/js_dict.js";
import * as Js_json from "bs-platform/lib/es6/js_json.js";
import * as Vaccine from "./Vaccine.bs.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";

function t_encode(v) {
  return Js_dict.fromArray([
              [
                "vaccine",
                Vaccine.t_encode(v.vaccine)
              ],
              [
                "adminedAt",
                $$Date.t_encode(v.adminedAt)
              ]
            ]);
}

function t_decode(v) {
  var dict = Js_json.classify(v);
  if (typeof dict === "number") {
    return Decco.error(undefined, "Not an object", v);
  }
  if (dict.TAG !== /* JSONObject */2) {
    return Decco.error(undefined, "Not an object", v);
  }
  var dict$1 = dict._0;
  var vaccine = Vaccine.t_decode(Belt_Option.getWithDefault(Js_dict.get(dict$1, "vaccine"), null));
  if (vaccine.TAG === /* Ok */0) {
    var adminedAt = $$Date.t_decode(Belt_Option.getWithDefault(Js_dict.get(dict$1, "adminedAt"), null));
    if (adminedAt.TAG === /* Ok */0) {
      return {
              TAG: /* Ok */0,
              _0: {
                vaccine: vaccine._0,
                adminedAt: adminedAt._0
              }
            };
    }
    var e = adminedAt._0;
    return {
            TAG: /* Error */1,
            _0: {
              path: ".adminedAt" + e.path,
              message: e.message,
              value: e.value
            }
          };
  }
  var e$1 = vaccine._0;
  return {
          TAG: /* Error */1,
          _0: {
            path: ".vaccine" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
}

export {
  t_encode ,
  t_decode ,
  
}
/* No side effect */
